DROP TABLE IF EXISTS nba_team CASCADE;

CREATE TABLE nba_team (
  id SERIAL PRIMARY KEY NOT NULL,
  team_id INTEGER NOT NULL UNIQUE,
  team_key VARCHAR(10) NOT NULL UNIQUE,
  city VARCHAR(255) NOT NULL,
  team_name VARCHAR(255) NOT NULL,
  conference VARCHAR(255) NOT NULL,
  division VARCHAR(255) NOT NULL,
  logo_url VARCHAR(255) NOT NULL
);