DROP TABLE IF EXISTS players_season_stats CASCADE;

-- previously player info
-- API endpoint: PlayerSeasonStats
CREATE TABLE players_season_stats (
  playerID INT  PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  team VARCHAR(255),
  position VARCHAR(255),
  games INT ,
  fantasyPoints FLOAT(4),
  minutes INT ,
  seconds INT ,
  fieldGoalsMade FLOAT(4),
  fieldGoalsAttempted FLOAT(4),
  fieldGoalsPercentage FLOAT(4),
  effectiveFieldGoalsPercentage FLOAT(4),
  twoPointersMade FLOAT(4),
  twoPointersAttempted FLOAT(4),
  twoPointersPercentage FLOAT(4),
  threePointersMade FLOAT(4),
  threePointersAttempted FLOAT(4),
  threePointersPercentage FLOAT(4),
  freeThrowsMade FLOAT(4),
  freeThrowsAttempted FLOAT(4),
  freeThrowsPercentage FLOAT(4),
  offensiveRebounds FLOAT(4),
  defensiveRebounds FLOAT(4),
  rebounds FLOAT(4),
  offensiveReboundsPercentage FLOAT(4),
  defensiveReboundsPercentage FLOAT(4),
  totalReboundsPercentage FLOAT(4),
  assists FLOAT(4),
  steals FLOAT(4),
  blockedShots FLOAT(4),
  turnovers FLOAT(4),
  personalFouls FLOAT(4),
  points FLOAT(4),
  trueShootingAttempts FLOAT(4),
  trueShootingPercentage FLOAT(4),
  playerEfficiencyRating FLOAT(4),
  assistsPercentage FLOAT(4),
  stealsPercentage FLOAT(4),
  blocksPercentage FLOAT(4),
  turnOversPercentage FLOAT(4),
  usageRatePercentage FLOAT(4),
  fantasyPointsFanDuel FLOAT(4),
  fantasyPointsDraftKings FLOAT(4),
  fantasyPointsYahoo FLOAT(4),
  plusMinus FLOAT(4),
  doubleDoubles FLOAT(4),
  tripleDoubles FLOAT(4),
  fantasyPointsFantasyDraft FLOAT(4)
);