DROP TABLE IF EXISTS player_info CASCADE;

CREATE TABLE player_info (
  id SERIAL PRIMARY KEY NOT NULL,
  playerId INTEGER NOT NULL UNIQUE,
  firstName VARCHAR(255) NOT NULL,
  lastName VARCHAR(255) NOT NULL,
  team VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  average_minutes INT  NOT NULL,
  average_seconds INT  NOT NULL,
  average_fieldGoalsMade INT  NOT NULL,
  average_fieldGoalsAttempted INT  NOT NULL,
  average_fieldGoalsPercentage INT  NOT NULL,
  average_effectiveFieldgoalsPercentage INT  NOT NULL,
  average_twoPointersMade INT  NOT NULL,
  average_twoPointersAttempted INT  NOT NULL,
  average_twoPointersPercentage INT  NOT NULL,
  average_threePointersMade INT  NOT NULL,
  average_threePointersAttempted INT  NOT NULL,
  average_threePointersPercentage INT  NOT NULL,
  average_freeThrowsMade INT  NOT NULL,
  average_freeThrowsAttempted INT  NOT NULL,
  average_freeThrowsPercentage INT  NOT NULL,
  average_offensiveRebounds INT  NOT NULL,
  average_defensiveRebounds INT  NOT NULL,
  average_rebounds INT  NOT NULL,
  average_offensiveReboundsPercentage INT  NOT NULL,
  average_defensiveReboundsPercentage INT  NOT NULL,
  average_totalReboundsPercentage INT  NOT NULL,
  average_assists INT  NOT NULL,
  average_steals INT  NOT NULL,
  average_blockedShots INT  NOT NULL,
  average_turnovers INT  NOT NULL,
  average_personalFouls INT  NOT NULL,
  average_points INT  NOT NULL,
  average_trueShootingAttempts INT  NOT NULL,
  average_trueShootingPercentage INT  NOT NULL,
  average_playerEfficiencyRating INT  NOT NULL,
  average_assistsPercentage INT  NOT NULL,
  average_stealsPercentage INT  NOT NULL,
  average_blocksPercentage INT  NOT NULL,
  average_turnoversPercentage INT  NOT NULL,
  average_usageRatePercentage INT  NOT NULL,
  average_plusMinus INT  NOT NULL,
  average_doubleDoubles INT  NOT NULL,
  average_tripleDoubles INT  NOT NULL,
  average_fantasyPointsfanduel INT  NOT NULL,
  average_fantasyPointsdraftkings INT  NOT NULL,
  average_fantasyPoints INT NOT NULL,
  average_fantasyPointsFantasyDraft INT NOT NULL 
);