DROP TABLE IF EXISTS players_season_stats CASCADE;

-- previously player info
-- API endpoint: PlayerSeasonStats
CREATE TABLE players_season_stats (
  id SERIAL PRIMARY KEY NOT NULL,
  player_id INT UNIQUE NOT NULL,
  games INT,
  minutes INT,
  seconds INT,
  field_goals_made FLOAT(4),
  field_goals_attempted FLOAT(4),
  field_goals_percentage FLOAT(4),
  effective_field_goals_percentage FLOAT(4),
  two_pointers_made FLOAT(4),
  two_pointers_attempted FLOAT(4),
  two_pointers_percentage FLOAT(4),
  three_pointers_made FLOAT(4),
  three_pointers_attempted FLOAT(4),
  three_pointers_percentage FLOAT(4),
  free_throws_made FLOAT(4),
  free_throws_attempted FLOAT(4),
  free_throws_percentage FLOAT(4),
  offensive_rebounds FLOAT(4),
  defensive_rebounds FLOAT(4),
  rebounds FLOAT(4),
  offensive_rebounds_percentage FLOAT(4),
  defensive_rebounds_percentage FLOAT(4),
  total_rebounds_percentage FLOAT(4),
  assists FLOAT(4),
  steals FLOAT(4),
  blocked_shots FLOAT(4),
  turnovers FLOAT(4),
  personal_fouls FLOAT(4),
  points FLOAT(4),
  true_shooting_attempts FLOAT(4),
  true_shooting_percentage FLOAT(4),
  player_efficiency_rating FLOAT(4),
  assists_percentage FLOAT(4),
  steals_percentage FLOAT(4),
  blocks_percentage FLOAT(4),
  turn_overs_percentage FLOAT(4),
  usage_rate_percentage FLOAT(4),
  fantasy_points_fan_duel FLOAT(4),
  fantasy_points_draft_kings FLOAT(4),
  fantasy_points_yahoo FLOAT(4),
  plus_minus FLOAT(4),
  double_doubles FLOAT(4),
  triple_doubles FLOAT(4),
  fantasy_points_fantasy_draft FLOAT(4)
);