DROP TABLE IF EXISTS players_game_stats CASCADE;

  -- API endpoint: PlayerGameStatsByDate
CREATE TABLE players_game_stats (
  id SERIAL PRIMARY KEY NOT NULL,
  statID INT  NOT NULL,
  teamID INT  NOT NULL,
  playerID INT REFERENCES players_season_stats(playerID) NOT NULL,
  seasonType INT  NOT NULL,
  season INT  NOT NULL,
  name VARCHAR(255) NOT NULL,
  team VARCHAR(255) NOT NULL,
  position  VARCHAR(255) NOT NULL,
  started INT  NOT NULL,
  fanDuelSalary INT  NOT NULL,
  draftKingsSalary INT  NOT NULL,
  fantasyDataSalary INT  NOT NULL,
  yahooSalary INT  NOT NULL,
  injuryStatus VARCHAR(255) NOT NULL,
  injuryBodyPart VARCHAR(255) NOT NULL,
  injuryStartDate VARCHAR(255),
  injuryNotes VARCHAR(255) NOT NULL,
  fanDuelPosition VARCHAR(255) NOT NULL,
  draftKingsPosition VARCHAR(255) NOT NULL,
  yahooPosition VARCHAR(255) NOT NULL,
  opponentRank INT  NOT NULL,
  opponentPositionRank INT  NOT NULL,
  globalTeamID INT  NOT NULL,
  fantasyDraftSalary INT,
  fantasyDraftPosition VARCHAR(255) NOT NULL,
  gameID INT  NOT NULL,
  opponentID INT  NOT NULL,
  opponent VARCHAR(255) NOT NULL,
  day VARCHAR(255) NOT NULL,
  dateTime VARCHAR(255) NOT NULL,
  homeOrAway VARCHAR(255) NOT NULL,
  isGameOver BOOLEAN, ---VARCHAR(255) NOT NULL, --boolean
  globalGameID INT  NOT NULL,
  globalOpponentID INT  NOT NULL,
  updated VARCHAR(255) NOT NULL,
  games INT  NOT NULL,
  fantasyPoints FLOAT(4),
  minutes INT  NOT NULL,
  seconds INT  NOT NULL,
  fieldGoalsMade FLOAT(4),
  fieldGoalsAttempted FLOAT(4),
  fieldGoalsPercentage FLOAT(4),
  effectiveFieldGoalsPercentage FLOAT(4),
  twoPointersMade FLOAT(4),
  twoPointersAttempted FLOAT(4),
  twoPointersPercentage FLOAT(4),
  threePointersMade FLOAT(4),
  threePointersAttempted FLOAT(4),
  threePointersPercentage FLOAT(4),
  freeThrowsMade FLOAT(4),
  freeThrowsAttempted FLOAT(4),
  freeThrowsPercentage  FLOAT(4),
  offensiveRebounds FLOAT(4),
  defensiveRebounds FLOAT(4),
  rebounds FLOAT(4),
  offensiveReboundsPercentage FLOAT(4),
  defensiveReboundsPercentage FLOAT(4),
  totalReboundsPercentage FLOAT(4),
  assists FLOAT(4),
  steals FLOAT(4),
  blockedShots FLOAT(4),
  turnovers FLOAT(4),
  personalFouls FLOAT(4),
  points FLOAT(4),
  trueShootingAttempts FLOAT(4),
  trueShootingPercentage FLOAT(4),
  playerEfficiencyRating FLOAT(4),
  assistsPercentage FLOAT(4),
  stealsPercentage FLOAT(4),
  blocksPercentage FLOAT(4),
  turnOversPercentage FLOAT(4),
  usageRatePercentage FLOAT(4),
  fantasyPointsFanDuel FLOAT(4),
  fantasyPointsDraftKings FLOAT(4),
  fantasyPointsYahoo FLOAT(4),
  plusMinus FLOAT(4),
  doubleDoubles FLOAT(4),
  tripleDoubles FLOAT(4),
  fantasyPointsFantasyDraft FLOAT(4),
  isClosed BOOLEAN,
  lineupConfirmed BOOLEAN, --VARCHAR(255) NOT NULL, --boolean
  lineupStatus VARCHAR(255) NOT NULL
);